script: skip
jobs:
  include:
  - stage: Build
    if: ( branch != master ) AND ( type = push )
    script:
    - sudo apt-get install tidy
    - tidy static/index.html || true
  - stage: Deploy
    if: ( branch = master ) AND ( type = push )
    script:
    - wget https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
    - unzip terraform_0.11.8_linux_amd64.zip
    - rm terraform_0.11.8_linux_amd64.zip
    - ./terraform init -backend-config="bucket=${TF_VAR_DOMAIN}" -backend-config="key=master.tfstate"
    - ./terraform apply -auto-approve
