install:
- wget https://releases.hashicorp.com/terraform/0.12.0-rc1/terraform_0.12.0-rc1_linux_amd64.zip
- unzip terraform_0.12.0-rc1_linux_amd64.zip
- rm terraform_0.12.0-rc1_linux_amd64.zip
script: skip
jobs:
  include:
  - stage: Build
    if: ( branch != master ) AND ( type = push )
    script:
    - sudo apt-get install tidy
    - tidy static/index.html || true
    - ./terraform init -backend-config="bucket=${TF_VAR_DOMAIN}" -backend-config="key=master.tfstate"
    - ./terraform plan
  - stage: Deploy
    if: ( branch = master ) AND ( type = push )
    script:
    - ./terraform init -backend-config="bucket=${TF_VAR_DOMAIN}" -backend-config="key=master.tfstate"
    - ./terraform apply -auto-approve
