script: skip
jobs:
  include:
  - stage: Lint
    if: ( branch != master ) AND (type = push)
    script:
    - sudo apt-get install tidy
    - tidy static/index.html || true
  - stage: Deploy
    if: ( branch = master ) AND (type = push)
    script: skip
    deploy:
      provider: s3
      bucket: queer.church
      region: us-east-1
      local_dir: static
      acl: public_read
  - stage: Actualize
    if: type = api
    script:
    - wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
    - unzip terraform_0.11.7_linux_amd64.zip
    - sudo mv terraform /usr/local/bin/
    - rm terraform_0.11.7_linux_amd64.zip
    - cd infra && terraform init && terraform apply -auto-approve
    - git remote add target "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
    - git add -A
    - git commit -m "ACTUALIZE ${TRAVIS_BUILD_NUMBER}"
    - git push target HEAD:$TRAVIS_BRANCH
